spring.application.name=StayEase

server.port = 9090

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/stayease
spring.datasource.username=postgres
spring.datasource.password=admin
# create schema on startup, drop on shutdown
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# log all SQL statements
spring.jpa.show-sql=true
# format hibernate queries
spring.jpa.properties.hibernate.format_sql=true

#security configs
spring.security.user.name=rushikesh
spring.security.user.password=pass

#jwt configs
jwt.secret=dummy-secret
