spring.application.name=StayEase

server.port = 9090

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/stayease
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
# create schema on startup, drop on shutdown
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# log all SQL statements
spring.jpa.show-sql=true
# format hibernate queries
spring.jpa.properties.hibernate.format_sql=true

#security configs
spring.security.user.name=${SECURITY_USER_NAME}
spring.security.user.password=${SECURITY_USER_PASSWORD}
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.provider=google

#jwt configs
jwt.secret=${JWT_SECRET}
